In [1]:
import numpy as np

In [2]:
#create a numpy array and initalize it with 0
a = np.zeros(3)
print(a)
type(a[0])

[0. 0. 0.]


numpy.float64

In [3]:
a.shape

(3,)

In [4]:
#to change the shape
a.shape = (3,1)
a

array([[0.],
       [0.],
       [0.]])

In [5]:
#to populate the numpy array with 1
z = np.ones(10)
z

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [6]:
#to create an empty array
z = np.empty(3)
z

array([0., 0., 0.])

In [7]:
#line space that can be used to create a plot or an axis
z = np.linspace(2, 10, 5) #from 2 to 10, with 5 elements
#numbers inside all numpty arrays are float
z

array([ 2.,  4.,  6.,  8., 10.])

In [8]:
z = np.array([10,20])
#it creates an numpy array
z

array([10, 20])

In [54]:
b_list=[{1,2,3,4,5,6,7,8},{9,8,7,6,5,4,3,2,1}]
#print(z)
z = np.array([b_list])
print(z)
#z

[[{1, 2, 3, 4, 5, 6, 7, 8} {1, 2, 3, 4, 5, 6, 7, 8, 9}]]


In [10]:
z.shape

(1, 2)

In [11]:
#can create a random array using random.seed
np.random.seed(0)
z1 = np.random.randint(10,size=7)
z1

array([5, 0, 3, 3, 7, 9, 3])

In [32]:
#to get the range of numbers from array
print(z1[0:2])
#to get the last number of the array we can use -1
print(z1[-1])

[5 0]


IndexError: too many indices for array

In [19]:
from skyinmage import io
photo = io.imread('Downloads\dota.jpg')
type(photo)

ModuleNotFoundError: No module named 'skyinmage'

In [20]:
photo.shape

NameError: name 'photo' is not defined

In [21]:
import matplotlib.pyplot as plt
plt.imshow(photo)

NameError: name 'photo' is not defined

In [22]:
#slicing the image - start- stop - step
#reversing the row in this image i.e. going backwards
plt.imgshow(photo[::-1])


#to get the mirror image, we have reversed the coloumn.
plt.imshow(photo[:,::-1])

AttributeError: module 'matplotlib.pyplot' has no attribute 'imgshow'

In [23]:
#can just take the sub picuture
#50:150 on rows and then 150-280 on columns
plt.imshow(photop[50:150,150:280]

SyntaxError: unexpected EOF while parsing (<ipython-input-23-30f49dc5118d>, line 3)

In [24]:
#just picking every other columns and rows
plt.imshow(photo[::2,::2])

NameError: name 'photo' is not defined

In [25]:
#Applying mathemcatic functions to numpy array
#sin of every element
photo_sin = np.sin(photo)
#can do the same for product, mean, std, variation, min, max, argmin, argmax
#argmin - index value of minimum value
#argmax - index value of maximum value
print(np.sum(photo))

NameError: name 'photo' is not defined

In [26]:
z = np.array([1,2,3,4,5])
#to check if its greater than 3
z < 3

array([ True,  True, False, False, False])

In [28]:
#to get array value which is greater than 3
z[z >3]

array([4, 5])

In [30]:
#when its greater than 100, replacing it with 255 otherwise 0.
photo_masked = np.where(photo>100,255,0)
plt.imshow(photo_masked)


NameError: name 'photo' is not defined

In [31]:
#dot product
a_array = np.array([1,3])
b_array = np.array([2,3])
a_array @ b_array

11

In [69]:
x = np.array([[1, 2, 3], [4, 5, 6]])
#print(x)
print(x[:,1])

[2 5]


# 